name = "GregTech Odyssey"
version = "0.5.5-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41cd318760b4a992f322e659f3a067861d53822aedc1d97dbded61ded93d03d3"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
