blank_issues_enabled: true
contact_links:
  - name: "Discord Server"
    url: https://discord.gg/PxruFSbtCn
    about: "Join our Discord server for community discussions and quick help. / 加入我们的 Discord 服务器进行社区讨论和快速求助。"
  - name: "QQ Group"
    url: https://qm.qq.com/q/Pm3WkA85qw
    about: "Join our QQ group for community discussions and quick help. / 加入我们的 QQ 群进行社区讨论和快速求助。"

